/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromouvoirRouteImport } from './routes/promouvoir'
import { Route as MapRouteImport } from './routes/map'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiPublicSyncCronSecretRouteImport } from './routes/api/public/sync-cron-secret'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicBackfillImagesRouteImport } from './routes/api/public/backfill-images'

const PromouvoirRoute = PromouvoirRouteImport.update({
  id: '/promouvoir',
  path: '/promouvoir',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncCronSecretRoute = ApiPublicSyncCronSecretRouteImport.update({
  id: '/api/public/sync-cron-secret',
  path: '/api/public/sync-cron-secret',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackfillImagesRoute = ApiPublicBackfillImagesRouteImport.update({
  id: '/api/public/backfill-images',
  path: '/api/public/backfill-images',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/legal': typeof LegalRoute
  '/map': typeof MapRoute
  '/promouvoir': typeof PromouvoirRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/event/$id': typeof EventIdRoute
  '/api/public/backfill-images': typeof ApiPublicBackfillImagesRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/sync-cron-secret': typeof ApiPublicSyncCronSecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/legal': typeof LegalRoute
  '/map': typeof MapRoute
  '/promouvoir': typeof PromouvoirRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/event/$id': typeof EventIdRoute
  '/api/public/backfill-images': typeof ApiPublicBackfillImagesRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/sync-cron-secret': typeof ApiPublicSyncCronSecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/legal': typeof LegalRoute
  '/map': typeof MapRoute
  '/promouvoir': typeof PromouvoirRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/event/$id': typeof EventIdRoute
  '/api/public/backfill-images': typeof ApiPublicBackfillImagesRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/sync-cron-secret': typeof ApiPublicSyncCronSecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/legal'
    | '/map'
    | '/promouvoir'
    | '/api/sitemap.xml'
    | '/event/$id'
    | '/api/public/backfill-images'
    | '/api/public/ingest'
    | '/api/public/sync-cron-secret'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/legal'
    | '/map'
    | '/promouvoir'
    | '/api/sitemap.xml'
    | '/event/$id'
    | '/api/public/backfill-images'
    | '/api/public/ingest'
    | '/api/public/sync-cron-secret'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/legal'
    | '/map'
    | '/promouvoir'
    | '/api/sitemap.xml'
    | '/event/$id'
    | '/api/public/backfill-images'
    | '/api/public/ingest'
    | '/api/public/sync-cron-secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  LegalRoute: typeof LegalRoute
  MapRoute: typeof MapRoute
  PromouvoirRoute: typeof PromouvoirRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  EventIdRoute: typeof EventIdRoute
  ApiPublicBackfillImagesRoute: typeof ApiPublicBackfillImagesRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicSyncCronSecretRoute: typeof ApiPublicSyncCronSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promouvoir': {
      id: '/promouvoir'
      path: '/promouvoir'
      fullPath: '/promouvoir'
      preLoaderRoute: typeof PromouvoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-cron-secret': {
      id: '/api/public/sync-cron-secret'
      path: '/api/public/sync-cron-secret'
      fullPath: '/api/public/sync-cron-secret'
      preLoaderRoute: typeof ApiPublicSyncCronSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backfill-images': {
      id: '/api/public/backfill-images'
      path: '/api/public/backfill-images'
      fullPath: '/api/public/backfill-images'
      preLoaderRoute: typeof ApiPublicBackfillImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  LegalRoute: LegalRoute,
  MapRoute: MapRoute,
  PromouvoirRoute: PromouvoirRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  EventIdRoute: EventIdRoute,
  ApiPublicBackfillImagesRoute: ApiPublicBackfillImagesRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicSyncCronSecretRoute: ApiPublicSyncCronSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
